In [2]:
import tensorflow as tf
import numpy as np

In [70]:
params = np.random.randint(0, 10, size=(3, 6, 3))

In [71]:
paramstf = tf.convert_to_tensor(params, tf.float32)

In [72]:
idx = np.array([[[0, 2], 
                 [1, 1]],
                [[2, 0], 
                 [1, 1]],
                [[2, 0], 
                 [1, 1]]
               ]) # [3, 2, 2]

In [73]:
p1 = tf.print(paramstf)

In [74]:
idxtf = tf.convert_to_tensor(idx, tf.float32)

In [75]:
gat = tf.gather_nd(params, idx)

In [76]:
p = tf.print(gat)

In [77]:
s = tf.print('-----------')

In [78]:
with tf.Session() as sess:
    sess.run(p1)
    sess.run(s)
    sess.run(p)

[[[9 3 6]
  [8 5 2]
  [7 6 9]
  [0 5 4]
  [2 0 3]
  [1 4 7]]

 [[0 6 1]
  [0 2 8]
  [1 1 3]
  [5 0 0]
  [0 8 2]
  [3 0 8]]

 [[1 1 0]
  [6 2 8]
  [4 0 4]
  [7 6 7]
  [8 8 3]
  [9 0 4]]]
-----------
[[[7 6 9]
  [0 2 8]]

 [[1 1 0]
  [0 2 8]]

 [[1 1 0]
  [0 2 8]]]


In [24]:
a = np.random.randint(0, 10, size=(2, 3))

In [23]:
b = np.random.randint(0, 10, size=(2, 3))

In [25]:
at = tf.convert_to_tensor(a, tf.float32)

In [26]:
bt = tf.convert_to_tensor(b, tf.float32)

In [44]:
atp = tf.print('a: \n', at)

In [43]:
btp = tf.print('b: \n', bt)

In [45]:
abstc = tf.stack((a, b), axis=-1)

In [46]:
abcat = tf.concat((a, b), axis=-1)

In [52]:
abp = tf.print('stack -1:\n',abstc)

In [53]:
abcp = tf.print('concat -1:\n', abcat)

In [54]:
line = tf.print('------------------')

In [55]:
with tf.Session() as s:
    s.run(atp)
    s.run(btp)
    s.run(line)
    s.run(abp)
    s.run(line)
    s.run(abcp)

a: 
 [[6 4 3]
 [3 7 5]]
b: 
 [[8 2 6]
 [8 7 0]]
------------------
stack -1:
 [[[6 8]
  [4 2]
  [3 6]]

 [[3 8]
  [7 7]
  [5 0]]]
------------------
concat -1:
 [[6 4 3 8 2 6]
 [3 7 5 8 7 0]]


In [4]:
ta = tf.TensorArray(tf.float32, size=10)

In [8]:
inputs = tf.convert_to_tensor(np.random.randint(1, 10, size=(10,2,2)).astype(np.float32))

In [10]:
input_ta = ta.unstack(inputs)

In [14]:
tap = tf.print(input_ta.next())

AttributeError: 'TensorArray' object has no attribute 'next'

In [13]:
with tf.Session() as s:
    s.run(tap)